namespace Openflight
{
	public enum FltRecordType
	{
		Header = 1,
		Group = 2,
		Object = 4,
		Face = 5,
		PushLevel = 10,
		PopLevel = 11,
		DOF = 14,
		PushSubface = 19,
		PopSubface = 20,
		PushExtension = 21,
		PopExtension = 22,
		Continuation = 23,
		Comment = 31,
		ColorPalette = 32,
		LongID = 33,
		Matrix = 49,
		Vector = 50,
		MultiTexture = 52,
		UVList = 53,
		BinarySeparatingPlane = 55,
		Replicate = 60,
		InstanceReference = 61,
		InstanceDefinition = 62,
		ExternalReference = 63,
		TexturePalette = 64,
		VertexPalette = 67,
		VertexColor = 68,
		VertexColorNormal = 69,
		VertexColorNormalUV = 70,
		VertexColorUV = 71,
		VertexList = 72,
		LevelOfDetail = 73,
		BoundingBox = 74,
		RotateAboutPoint = 80,
		RotateScaleToPoint = 81,
		Put = 82,
		EyepointTrackplanePalette = 83,
		Mesh = 84,
		LocalVertexPool = 85,
		MeshPrimitive = 86,
		RoadSegment = 87,
		Switch = 96,
		PushAttribute = 122,
		PopAttribute = 123
	}
}
